export const groupSingle = {
  id: 1,
  name: "Group1",
  img: "/default_group_pic.png",
  tags: ["hobbies", "education", "gaming"],
  members: [{ id: 1 }, { id: 2 }, { id: 3 }],
};

export const groupsSmall = [
  {
    id: 1,
    name: "Group1",
    img: "/deafult_group_pic.png",
    tags: ["education"],
    members: [{ id: 1 }, { id: 2 }, { id: 3 }],
  },
  {
    id: 2,
    name: "Group2",
    img: "/deafult_group_pic.png",
    tags: ["education"],
    members: [{ id: 2 }, { id: 4 }, { id: 6 }],
  },
  {
    id: 3,
    name: "Group3",
    img: "/deafult_group_pic.png",
    tags: ["hobbies", "gaming", "education"],
    members: [{ id: 1 }, { id: 3 }, { id: 5 }],
  },
  {
    id: 4,
    name: "Group4",
    img: "/default_group_pic.png",
    tags: ["food", "travel", "miscellaneous"],
    members: [{ id: 2 }, { id: 4 }],
  },
  {
    id: 5,
    name: "Group5",
    img: "/default_group_pic.png",
    tags: ["business", "hobbies", "gaming"],
    members: [{ id: 1 }, { id: 5 }],
  },
  {
    id: 6,
    name: "Group6",
    img: "/default_group_pic.png",
    tags: ["education", "health", "pets"],
    members: [{ id: 3 }, { id: 4 }],
  },
  {
    id: 7,
    name: "Group7",
    img: "/default_group_pic.png",
    tags: ["travel", "food", "business"],
    members: [{ id: 2 }, { id: 5 }],
  },
  {
    id: 8,
    name: "Group8",
    img: "/default_group_pic.png",
    tags: ["gaming", "hobbies", "miscellaneous"],
    members: [{ id: 1 }, { id: 3 }],
  },
  {
    id: 9,
    name: "Group9",
    img: "/default_group_pic.png",
    tags: ["education", "health", "pets"],
    members: [{ id: 4 }, { id: 5 }],
  },
];

export const groupsMedium = [
  {
    id: 1,
    name: "Group1",
    img: "/default_group_pic.png",
    tags: ["hobbies", "education", "gaming"],
  },
  {
    id: 2,
    name: "Group2",
    img: "/default_group_pic.png",
    tags: ["food", "travel", "business"],
  },
  {
    id: 3,
    name: "Group3",
    img: "/default_group_pic.png",
    tags: ["health", "pets", "miscellaneous"],
  },
  {
    id: 4,
    name: "Group4",
    img: "/default_group_pic.png",
    tags: ["education", "gaming", "hobbies"],
  },
  {
    id: 5,
    name: "Group5",
    img: "/default_group_pic.png",
    tags: ["travel", "food", "business"],
  },
  {
    id: 6,
    name: "Group6",
    img: "/default_group_pic.png",
    tags: ["health", "education", "pets"],
  },
  {
    id: 7,
    name: "Group7",
    img: "/default_group_pic.png",
    tags: ["gaming", "hobbies", "miscellaneous"],
  },
  {
    id: 8,
    name: "Group8",
    img: "/default_group_pic.png",
    tags: ["business", "travel", "food"],
  },
  {
    id: 9,
    name: "Group9",
    img: "/default_group_pic.png",
    tags: ["education", "health", "pets"],
  },
  {
    id: 10,
    name: "Group10",
    img: "/default_group_pic.png",
    tags: ["hobbies", "gaming", "miscellaneous"],
  },
  {
    id: 11,
    name: "Group11",
    img: "/default_group_pic.png",
    tags: ["travel", "business", "food"],
  },
  {
    id: 12,
    name: "Group12",
    img: "/default_group_pic.png",
    tags: ["health", "education", "pets"],
  },
  {
    id: 13,
    name: "Group13",
    img: "/default_group_pic.png",
    tags: ["gaming", "hobbies", "education"],
  },
  {
    id: 14,
    name: "Group14",
    img: "/default_group_pic.png",
    tags: ["business", "travel", "miscellaneous"],
  },
  {
    id: 15,
    name: "Group15",
    img: "/default_group_pic.png",
    tags: ["food", "health", "pets"],
  },
  {
    id: 16,
    name: "Group16",
    img: "/default_group_pic.png",
    tags: ["education", "gaming", "hobbies"],
  },
  {
    id: 17,
    name: "Group17",
    img: "/default_group_pic.png",
    tags: ["travel", "business", "food"],
  },
  {
    id: 18,
    name: "Group18",
    img: "/default_group_pic.png",
    tags: ["travel"],
  },
  {
    id: 19,
    name: "Group19",
    img: "/default_group_pic.png",
    tags: ["business", "food"],
  },
];

export const groupsLarge = [
  {
    id: 1,
    name: "Group1",
    img: "/default_group_pic.png",
    tags: ["hobbies", "education", "gaming"],
  },
  {
    id: 2,
    name: "Group2",
    img: "/default_group_pic.png",
    tags: ["food", "travel", "business"],
  },
  {
    id: 3,
    name: "Group3",
    img: "/default_group_pic.png",
    tags: ["health", "pets", "miscellaneous"],
  },
  {
    id: 4,
    name: "Group4",
    img: "/default_group_pic.png",
    tags: ["education", "gaming", "hobbies"],
  },
  {
    id: 5,
    name: "Group5",
    img: "/default_group_pic.png",
    tags: ["travel", "food", "business"],
  },
  {
    id: 6,
    name: "Group6",
    img: "/default_group_pic.png",
    tags: ["health", "education", "pets"],
  },
  {
    id: 7,
    name: "Group7",
    img: "/default_group_pic.png",
    tags: ["gaming", "hobbies", "miscellaneous"],
  },
  {
    id: 8,
    name: "Group8",
    img: "/default_group_pic.png",
    tags: ["business", "travel", "food"],
  },
  {
    id: 9,
    name: "Group9",
    img: "/default_group_pic.png",
    tags: ["education", "health", "pets"],
  },
  {
    id: 10,
    name: "Group10",
    img: "/default_group_pic.png",
    tags: ["hobbies", "gaming", "miscellaneous"],
  },
  {
    id: 11,
    name: "Group11",
    img: "/default_group_pic.png",
    tags: ["travel", "business", "food"],
  },
  {
    id: 12,
    name: "Group12",
    img: "/default_group_pic.png",
    tags: ["health", "education", "pets"],
  },
  {
    id: 13,
    name: "Group13",
    img: "/default_group_pic.png",
    tags: ["gaming", "hobbies", "education"],
  },
  {
    id: 14,
    name: "Group14",
    img: "/default_group_pic.png",
    tags: ["business", "travel", "miscellaneous"],
  },
  {
    id: 15,
    name: "Group15",
    img: "/default_group_pic.png",
    tags: ["food", "health", "pets"],
  },
  {
    id: 16,
    name: "Group16",
    img: "/default_group_pic.png",
    tags: ["education", "gaming", "hobbies"],
  },
  {
    id: 17,
    name: "Group17",
    img: "/default_group_pic.png",
    tags: ["travel", "business", "food"],
  },
  {
    id: 18,
    name: "Group18",
    img: "/default_group_pic.png",
    tags: ["health", "education", "pets"],
  },
  {
    id: 19,
    name: "Group19",
    img: "/default_group_pic.png",
    tags: ["gaming", "hobbies", "miscellaneous"],
  },
  {
    id: 20,
    name: "Group20",
    img: "/default_group_pic.png",
    tags: ["business", "travel", "food"],
  },
  {
    id: 21,
    name: "Group21",
    img: "/default_group_pic.png",
    tags: ["education", "health", "pets"],
  },
  {
    id: 22,
    name: "Group22",
    img: "/default_group_pic.png",
    tags: ["hobbies", "gaming", "miscellaneous"],
  },
  {
    id: 23,
    name: "Group23",
    img: "/default_group_pic.png",
    tags: ["travel", "business", "food"],
  },
  {
    id: 24,
    name: "Group24",
    img: "/default_group_pic.png",
    tags: ["health", "education", "pets"],
  },
  {
    id: 25,
    name: "Group25",
    img: "/default_group_pic.png",
    tags: ["gaming", "hobbies", "education"],
  },
  {
    id: 26,
    name: "Group26",
    img: "/default_group_pic.png",
    tags: ["business", "travel", "miscellaneous"],
  },
  {
    id: 27,
    name: "Group27",
    img: "/default_group_pic.png",
    tags: ["food", "health", "pets"],
  },
  {
    id: 28,
    name: "Group28",
    img: "/default_group_pic.png",
    tags: ["education", "gaming", "hobbies"],
  },
  {
    id: 29,
    name: "Group29",
    img: "/default_group_pic.png",
    tags: ["travel", "business", "food"],
  },
  {
    id: 30,
    name: "Group30",
    img: "/default_group_pic.png",
    tags: ["health", "education", "pets"],
  },
  {
    id: 31,
    name: "Group31",
    img: "/default_group_pic.png",
    tags: ["gaming", "hobbies", "miscellaneous"],
  },
  {
    id: 32,
    name: "Group32",
    img: "/default_group_pic.png",
    tags: ["business", "travel", "food"],
  },
  {
    id: 33,
    name: "Group33",
    img: "/default_group_pic.png",
    tags: ["education", "health", "pets"],
  },
  {
    id: 34,
    name: "Group34",
    img: "/default_group_pic.png",
    tags: ["hobbies", "gaming", "education"],
  },
  {
    id: 35,
    name: "Group35",
    img: "/default_group_pic.png",
    tags: ["travel", "business", "miscellaneous"],
  },
  {
    id: 36,
    name: "Group36",
    img: "/default_group_pic.png",
    tags: ["food", "health", "pets"],
  },
  {
    id: 37,
    name: "Group37",
    img: "/default_group_pic.png",
    tags: ["education", "gaming", "hobbies"],
  },
  {
    id: 38,
    name: "Group38",
    img: "/default_group_pic.png",
    tags: ["health", "education", "pets"],
  },
  {
    id: 39,
    name: "Group39",
    img: "/default_group_pic.png",
    tags: ["gaming", "hobbies", "miscellaneous"],
  },
  {
    id: 40,
    name: "Group40",
    img: "/default_group_pic.png",
    tags: ["business", "travel", "food"],
  },
  {
    id: 41,
    name: "Group41",
    img: "/default_group_pic.png",
    tags: ["education", "health", "pets"],
  },
  {
    id: 42,
    name: "Group42",
    img: "/default_group_pic.png",
    tags: ["hobbies", "gaming", "miscellaneous"],
  },
  {
    id: 43,
    name: "Group43",
    img: "/default_group_pic.png",
    tags: ["travel", "business", "food"],
  },
  {
    id: 44,
    name: "Group44",
    img: "/default_group_pic.png",
    tags: ["health", "education", "pets"],
  },
  {
    id: 45,
    name: "Group45",
    img: "/default_group_pic.png",
    tags: ["gaming", "hobbies", "education"],
  },
  {
    id: 46,
    name: "Group46",
    img: "/default_group_pic.png",
    tags: ["business", "travel", "miscellaneous"],
  },
  {
    id: 47,
    name: "Group47",
    img: "/default_group_pic.png",
    tags: ["food", "health", "pets"],
  },
  {
    id: 48,
    name: "Group48",
    img: "/default_group_pic.png",
    tags: ["education", "gaming", "hobbies"],
  },
  {
    id: 49,
    name: "Group49",
    img: "/default_group_pic.png",
    tags: ["gaming", "health"],
  },
  {
    id: 50,
    name: "Group50",
    img: "/default_group_pic.png",
    tags: ["health"],
  },
];
